[package]
name = "iota-curl"
version = "0.1.0"
authors = ["Paul D Handy <paul@pauldhandy.com>",
           "Andreas C. Osowski <andreas@osowski.de>"]
keywords = ["no_std"]

[dependencies]
iota-trytes = { path = "../trytes" }
